### ISSUE TITLE
Class "dropdown-toggle" should be removed from name buttons

### ISSUE THREAD

**Issue by KevinGreene** [heroesofthestorm/heroesofthestorm.github.io#1]
Currently the class dropdown-toggle is on names, causing a weird UI issue for me (Chrome, Mac OS X)

![free_hero_rotation](https://cloud.githubusercontent.com/assets/320528/5807679/964db510-9ff3-11e4-883c-0fe50adec725.png)

Notice how the right side of the "Brightwing Button" is curved.

Removing the class dropdown-toggle fixes this, as evidenced here:

![free_hero_rotation-2](https://cloud.githubusercontent.com/assets/320528/5807705/ba457f8e-9ff3-11e4-9899-b767825e7405.png)

The dropdown still functions correctly, as it still has the data-toggle.

Not sure if there is a generator for this, or if all the edits are manual, but this is a small thing that would make the page look better, I feel.

**Comment by heroesofthestorm** [comment]
Done, thanks for the suggestion!
